version: '3'
services:
  mysql:
   image: mysql:5.7
   container_name: mysql_prive
   restart: always
   ports:
     - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USER: "root"
     MYSQL_PASSWORD: "root"
     MYSQL_DATABASE: challenge
   volumes:
     - ~/container-data/mysql:/var/lib/mysql
   platform: linux/amd64
  order-app:
   image: order-app:latest
   container_name: order-app
   restart: on-failure
   ports:
   - "8080:8080"
   environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/challenge
  broker-app:
    image: broker-app:latest
    container_name: broker-app
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/challenge