spring:
  profiles: ide
  redis:
    host: 127.0.0.1
    database: 4
    timeout: 5000
  datasource:
    url: jdbc:mysql://localhost:3306/challenge?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    root: debug